basePath: /filemanage 基础路劲
definitions:
  handler.Result:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      msg:
        example: ok
        type: string
    type: object
host: localhost:23456
info:
  contact: {}
  description: 文件管理服务API文档
  title: fzk API
  version: "1.0"
paths:
  /deleteFileList:
    post:
      description: 服务器上普通文件或图片删除
      parameters:
      - description: 文件的访问url1,文件的访问url2...
        in: body
        name: fileUrls
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Result'
      summary: 删除文件列表
      tags:
      - filemanage
  /fileList:
    get:
      description: 获取服务器上普通文件或图片的访问列表
      parameters:
      - description: 文件类型：file or image
        in: query
        name: fileType
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handler.Result'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
      summary: 获取服务器上普通文件或图片的访问列表
      tags:
      - filemanage
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: 上传普通文件或图片
      parameters:
      - description: 相对路径
        in: body
        name: relativePath
        required: true
        schema:
          type: string
      - description: 文件用途
        in: body
        name: type
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Result'
      summary: 上传文件
      tags:
      - filemanage
swagger: "2.0"
